name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Buildd docker image
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "elbart"
          password: ${{ secrets.PAT }}
          repository: elbart/pecunia
          tags: latest
